---
deployment:
  tasks:
    - export DEPLOYPATH=/home/puls0278/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH  
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
    - /bin/rm -rf $DEPLOYPATH/.git
